/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import { ReportAnalysisResult } from '../types';
import { Stethoscope, CheckCircle2, HelpCircle, AlertCircle } from 'lucide-react';

interface PrintableReportViewProps {
  analysis: ReportAnalysisResult;
}

export const PrintableReportView: React.FC<PrintableReportViewProps> = ({ analysis }) => {
  return (
    <div id="printable-area" className="hidden print:block bg-white text-slate-900 p-8 max-w-4xl mx-auto space-y-6">
      
      {/* Print Header */}
      <div className="border-b-2 border-slate-900 pb-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-blue-600 text-white flex items-center justify-center font-bold">
            <Stethoscope className="w-6 h-6" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-slate-900">MediExplain</h1>
            <p className="text-xs text-slate-500">Patient Educational Summary Sheet</p>
          </div>
        </div>

        <div className="text-right text-xs text-slate-600">
          <div>Report Date: {analysis.patientInfo?.date || new Date().toLocaleDateString()}</div>
          <div>Document: {analysis.fileName}</div>
        </div>
      </div>

      {/* Safety Disclaimer */}
      <div className="p-3 bg-slate-100 rounded-lg text-xs text-slate-700 italic border border-slate-300">
        <strong>Educational Disclaimer:</strong> This summary is generated by AI for educational preparation purposes and does not substitute for medical advice or clinical diagnosis.
      </div>

      {/* Summary */}
      <div className="space-y-2">
        <h2 className="text-base font-bold border-b border-slate-300 pb-1 uppercase tracking-wide">
          1. Executive Summary
        </h2>
        <p className="text-sm leading-relaxed">{analysis.shortSummary}</p>
      </div>

      {/* Layman Explanation */}
      <div className="space-y-2">
        <h2 className="text-base font-bold border-b border-slate-300 pb-1 uppercase tracking-wide">
          2. Patient-Friendly Explanation
        </h2>
        <p className="text-sm leading-relaxed">{analysis.laymanExplanation}</p>
      </div>

      {/* Lab Values Table */}
      <div className="space-y-2">
        <h2 className="text-base font-bold border-b border-slate-300 pb-1 uppercase tracking-wide">
          3. Extracted Lab Test Measurements
        </h2>
        <table className="w-full text-left text-xs border-collapse">
          <thead>
            <tr className="border-b-2 border-slate-400 bg-slate-50">
              <th className="py-2 px-1">Test Name</th>
              <th className="py-2 px-1">Result</th>
              <th className="py-2 px-1">Reference Range</th>
              <th className="py-2 px-1">Status</th>
            </tr>
          </thead>
          <tbody>
            {analysis.labValues.map((v) => (
              <tr key={v.id} className="border-b border-slate-200">
                <td className="py-2 px-1 font-semibold">{v.name}</td>
                <td className="py-2 px-1 font-bold">{v.value} {v.unit}</td>
                <td className="py-2 px-1">{v.referenceRange}</td>
                <td className="py-2 px-1 font-semibold uppercase">{v.status}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Top Questions for Doctor */}
      <div className="space-y-2">
        <h2 className="text-base font-bold border-b border-slate-300 pb-1 uppercase tracking-wide">
          4. Recommended Questions for Your Healthcare Visit
        </h2>
        <ol className="list-decimal list-inside space-y-1.5 text-xs">
          {(analysis.doctorPrep?.topQuestions || []).map((q) => (
            <li key={q.id} className="font-medium">
              "{q.question}" <span className="text-slate-500">({q.context})</span>
            </li>
          ))}
        </ol>
      </div>

    </div>
  );
};
