/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { MedicalTerm } from '../types';
import { Language } from '../utils/i18n';

export const GLOSSARY_EN: MedicalTerm[] = [
  {
    term: 'HDL (High-Density Lipoprotein)',
    definition: 'Known as "good cholesterol", HDL removes excess cholesterol from the blood and takes it back to the liver to be broken down.',
    whyItMatters: 'Higher HDL levels protect against clogged arteries and reduce heart attack risk.',
    analogy: 'A street sweeper truck clearing garbage off arterial roads.',
    category: 'Cardiology & Lipids'
  },
  {
    term: 'LDL (Low-Density Lipoprotein)',
    definition: 'Often termed "bad cholesterol", LDL transports fatty cholesterol from the liver into tissues and blood vessel walls.',
    whyItMatters: 'Excess LDL can build up inside artery walls, forming narrow plaques that hinder blood flow.',
    analogy: 'Cargo trucks depositing excess boxes in narrow hallways.',
    category: 'Cardiology & Lipids'
  },
  {
    term: 'Triglycerides',
    definition: 'The primary form of fat stored in the body, derived from calories, sugars, and fats you consume but do not immediately burn.',
    whyItMatters: 'High levels contribute to hardening of arteries and increase risk of metabolic issues or pancreatitis.',
    analogy: 'Extra battery reserves stored in your body when fuel isn\'t burned right away.',
    category: 'Cardiology & Lipids'
  },
  {
    term: 'eGFR (Estimated Glomerular Filtration Rate)',
    definition: 'A mathematical estimate of how well your kidney filters clear waste products from your blood.',
    whyItMatters: 'A score above 60 indicates healthy kidney function; lower numbers prompt kidney health checks.',
    analogy: 'The gallon-per-minute flow rate of a clean water filtration system.',
    category: 'Nephrology'
  },
  {
    term: 'Creatinine',
    definition: 'A natural waste product generated by normal muscle movement and breakdown that is filtered out by the kidneys.',
    whyItMatters: 'High blood creatinine can mean kidney filters are sluggish or dehydrating.',
    analogy: 'Dust produced by room fans that clean-up crews (kidneys) vacuum away.',
    category: 'Nephrology'
  },
  {
    term: 'ALT (Alanine Aminotransferase)',
    definition: 'An enzyme produced primarily inside liver cells.',
    whyItMatters: 'When liver cells are stressed or inflamed, ALT leaks out into the blood stream.',
    analogy: 'Engine fluid leaking onto the garage floor when an engine gets hot.',
    category: 'Hepatology'
  },
  {
    term: 'AST (Aspartate Aminotransferase)',
    definition: 'An enzyme found in liver, heart muscle, and skeletal muscle tissue.',
    whyItMatters: 'Elevated AST along with ALT helps assess liver or muscle stress.',
    analogy: 'A secondary warning sensor shared between the engine and electrical system.',
    category: 'Hepatology'
  },
  {
    term: 'HbA1c (Glycated Hemoglobin)',
    definition: 'A blood test measuring the percentage of hemoglobin proteins in your red blood cells coated with sugar over the last 2 to 3 months.',
    whyItMatters: 'Provides an accurate long-term picture of blood sugar control beyond single fasting readings.',
    analogy: 'A quarterly report card showing average speed over months rather than a single radar gun snapshot.',
    category: 'Endocrinology'
  },
  {
    term: 'hs-CRP (High-Sensitivity C-Reactive Protein)',
    definition: 'A liver-produced protein that rises when low-grade inflammation is present in arterial walls or body tissue.',
    whyItMatters: 'Serves as an indicator for cardiovascular inflammation risk.',
    analogy: 'A sensitive smoke detector picking up smoldering embers before a fire starts.',
    category: 'Cardiology & Inflammation'
  },
  {
    term: 'Hemoglobin',
    definition: 'An iron-rich protein inside red blood cells that carries oxygen from your lungs to the rest of your body.',
    whyItMatters: 'Low hemoglobin causes fatigue and anemia; high levels can occur from dehydration or lung conditions.',
    analogy: 'Oxygen delivery trucks driving around to keep every neighborhood energized.',
    category: 'Hematology'
  },
  {
    term: 'Platelets (Thrombocytes)',
    definition: 'Tiny disc-shaped blood cells that clump together to stop bleeding when blood vessels are damaged.',
    whyItMatters: 'Too low risks bleeding/bruising; too high can increase clotting tendencies.',
    analogy: 'Tiny emergency road workers who instantly seal potholes and leaks.',
    category: 'Hematology'
  },
  {
    term: 'WBC (White Blood Cells)',
    definition: 'Immune system cells that defend your body against viral, bacterial, and fungal infections.',
    whyItMatters: 'Elevated levels often indicate an active infection or inflammation; low levels suggest immune vulnerability.',
    analogy: 'The body\'s active defense force responding to security alerts.',
    category: 'Hematology & Immunology'
  },
  {
    term: 'TSH (Thyroid Stimulating Hormone)',
    definition: 'A pituitary gland hormone that signals the thyroid gland to release metabolism-regulating hormones.',
    whyItMatters: 'High TSH means the thyroid is underactive (hypothyroidism); low TSH means overactive (hyperthyroidism).',
    analogy: 'The thermostat dial calling for more or less furnace heat in a room.',
    category: 'Endocrinology'
  },
  {
    term: 'BUN (Blood Urea Nitrogen)',
    definition: 'A waste product formed in the liver from breaking down proteins, which is excreted by the kidneys.',
    whyItMatters: 'Used alongside creatinine to assess kidney function and hydration state.',
    analogy: 'Exhaust fumes produced during engine operation.',
    category: 'Nephrology'
  }
];

export const GLOSSARY_FR: MedicalTerm[] = [
  {
    term: 'HDL (Cholestérol HDL)',
    definition: 'Connu sous le nom de "bon cholestérol", le HDL élimine l\'excès de graisse dans le sang et le transporte vers le foie pour être décomposé.',
    whyItMatters: 'Des niveaux élevés de HDL protègent les artères et réduisent les risques d\'accident cardiovasculaire.',
    analogy: 'Une balayeuse de rue qui nettoie les déchets sur les grandes artères.',
    category: 'Cardiologie & Lipides'
  },
  {
    term: 'LDL (Cholestérol LDL)',
    definition: 'Souvent appelé "mauvais cholestérol", le LDL transporte le cholestérol du foie vers les vaisseaux sanguins.',
    whyItMatters: 'L\'excès de LDL peut s\'accumuler dans les parois artérielles et former des plaques réduisant le flux sanguin.',
    analogy: 'Des camions de livraison déposant des cartons encombrants dans un couloir étroit.',
    category: 'Cardiologie & Lipides'
  },
  {
    term: 'Triglycérides',
    definition: 'Forme principale de graisse stockée dans le corps, provenant des calories, sucres et graisses consommés non brûlés immédiatement.',
    whyItMatters: 'Des taux élevés contribuent à la rigidité artérielle et augmentent le risque métabolique.',
    analogy: 'Des batteries de réserve stockées lorsque l\'énergie n\'est pas consommée tout de suite.',
    category: 'Cardiologie & Lipides'
  },
  {
    term: 'eGFR (Débit de Filtration Glomérulaire)',
    definition: 'Estimation mathématique de l\'efficacité avec laquelle vos reins filtrent les déchets du sang.',
    whyItMatters: 'Un score supérieur à 60 indique une bonne fonction rénale.',
    analogy: 'Le débit en litres par minute d\'un filtre à eau domestique.',
    category: 'Néphrologie'
  },
  {
    term: 'Créatinine',
    definition: 'Déchet naturel produit par le fonctionnement musculaire normal, éliminé par les reins.',
    whyItMatters: 'Une créatinine élevée peut signaler un ralentissement du filtrage rénal ou une déshydratation.',
    analogy: 'La poussière accumulée aspirée régulièrement par les équipes d\'entretien (les reins).',
    category: 'Néphrologie'
  },
  {
    term: 'ALT (Alanine Aminotransférase)',
    definition: 'Enzyme produite principalement dans les cellules du foie.',
    whyItMatters: 'Lorsque le foie est sous tension ou enflammé, l\'ALT s\'échappe dans la circulation sanguine.',
    analogy: 'Du liquide de moteur qui fuit sur le sol lorsque le moteur chauffe.',
    category: 'Hépatologie'
  },
  {
    term: 'AST (Aspartate Aminotransférase)',
    definition: 'Enzyme présente dans le foie, le cœur et les tissus musculaires.',
    whyItMatters: 'Son élévation avec l\'ALT aide à évaluer l\'effort du foie ou des muscles.',
    analogy: 'Un voyant d\'avertissement secondaire partagé entre le moteur et le système électrique.',
    category: 'Hépatologie'
  },
  {
    term: 'HbA1c (Hémoglobine Glyquée)',
    definition: 'Examen mesurant le pourcentage moyen de sucre fixé sur les globules rouges au cours des 2 à 3 derniers mois.',
    whyItMatters: 'Donne une vision précise du contrôle de la glycémie à long terme.',
    analogy: 'Un bulletin de notes trimestriel montrant la vitesse moyenne sur des mois plutôt qu\'un simple contrôle de vitesse.',
    category: 'Endocrinologie'
  },
  {
    term: 'hs-CRP (Protéine C-Réactive Ultra-Sensible)',
    definition: 'Protéine hépatique augmentant lors d\'une inflammation vasculaire ou tissulaire.',
    whyItMatters: 'Indicateur précoce du risque d\'inflammation cardiovasculaire.',
    analogy: 'Un détecteur de fumée très sensible détectant des braises couvant avant le feu.',
    category: 'Cardiologie & Inflammation'
  },
  {
    term: 'Hémoglobine',
    definition: 'Protéine riche en fer contenue dans les globules rouges transportant l\'oxygène des poumons vers le corps.',
    whyItMatters: 'Une faible hémoglobine provoque de la fatigue (anémie).',
    analogy: 'Des camions de livraison d\'oxygène alimentant chaque quartier en énergie.',
    category: 'Hématologie'
  },
  {
    term: 'Plaquettes (Thrombocytes)',
    definition: 'Petites cellules sanguines qui s\'agrègent pour stopper les saignements lors d\'une blessure.',
    whyItMatters: 'Essentielles pour la coagulation et la cicatrisation.',
    analogy: 'Des agents d\'urgence qui colmatent immédiatement les fuites de canalisation.',
    category: 'Hématologie'
  },
  {
    term: 'WBC (Leucocytes / Globules Blancs)',
    definition: 'Cellules du système immunitaire défendant le corps contre les infections.',
    whyItMatters: 'Des taux élevés indiquent souvent une infection ou une réaction inflammatoire.',
    analogy: 'La force de sécurité interne de l\'organisme répondant aux alerte de défense.',
    category: 'Hématologie & Immunologie'
  },
  {
    term: 'TSH (Hormone Thyréostimulante)',
    definition: 'Hormone de l\'hypophyse régulant l\'activité métabolique de la glande thyroïde.',
    whyItMatters: 'Permet d\'évaluer si la thyroïde fonctionne en sous-régime (hypothyroïdie) ou sur-régime (hyperthyroïdie).',
    analogy: 'Le bouton du thermostat demandant plus ou moins de chauffage dans la pièce.',
    category: 'Endocrinologie'
  },
  {
    term: 'BUN (Urée Sanguine)',
    definition: 'Déchet issu de la dégradation des protéines par le foie, éliminé par les reins.',
    whyItMatters: 'Évalue le fonctionnement rénal et le niveau d\'hydratation.',
    analogy: 'Les gaz d\'échappement produits lors du fonctionnement du moteur.',
    category: 'Néphrologie'
  }
];

export const GLOSSARY_AR: MedicalTerm[] = [
  {
    term: 'HDL (الكوليسترول الجيد)',
    definition: 'يُعرف بـ "الكوليسترول النافع"، حيث يقوم بإزالة الكوليسترول الزائد من الدم ونقله إلى الكبد للتخلص منه.',
    whyItMatters: 'ارتفاع مستويات HDL يحمي الشرايين ويقلل خطر الإصابة بأزمات قلبية.',
    analogy: 'شاحنة تنظيف الشوارع التي تزيل المخلفات من الطرق الشريانية.',
    category: 'أمراض القلب والكوليسترول'
  },
  {
    term: 'LDL (الكوليسترول الضار)',
    definition: 'يُعرف بـ "الكوليسترول الضار"، حيث ينقل الدهون من الكبد إلى جدران الأوعية الدموية.',
    whyItMatters: 'ارتفاعه يتسبب في تراكم ترسبات دهنية تضيق الشرايين وتعيق تدفق الدم.',
    analogy: 'شاحنات نقل تضع صناديق زائدة في ممر ضيق.',
    category: 'أمراض القلب والكوليسترول'
  },
  {
    term: 'الدهون الثلاثية (Triglycerides)',
    definition: 'الشكل الرئيسي للدهون المخزنة في الجسم الناتجة عن السعرات والسكريات الزائدة.',
    whyItMatters: 'ارتفاعها يساهم في تصلب الشرايين وزيادة مخاطر الأيض.',
    analogy: 'بطاريات إضافية مخزنة في جسمك عندما لا يتم استهلاك الوقود فترته.',
    category: 'أمراض القلب والكوليسترول'
  },
  {
    term: 'eGFR (معدل ترشيح الكلى المقدر)',
    definition: 'تقدير حسابي لمدى كفاءة مرشحات الكلى في تنقية الفضلات من الدم.',
    whyItMatters: 'درجة أعلى من 60 تشير إلى وظائف كلى سليمة.',
    analogy: 'معدل تدفق المياه النظيفة في نظام تصفية منزلي.',
    category: 'أمراض الكلى'
  },
  {
    term: 'الكرياتينين (Creatinine)',
    definition: 'مادة عادمة ناتجة عن النشاط العضلي الطبيعي ويتم تصفيتها عبر الكلى.',
    whyItMatters: 'ارتفاعه قد يشير إلى بطء في ترشيح الكلى أو الجفاف.',
    analogy: 'غبار ناتج عن تشغيل الأجهزة يتم شفطه بواسطة فريق التنظيف (الكلى).',
    category: 'أمراض الكلى'
  },
  {
    term: 'ALT (إنزيم الكبد)',
    definition: 'إنزيم يتواجد بشكل رئيسي داخل خلايا الكبد.',
    whyItMatters: 'عند تسرب الإنزيم للدم يشير ذلك إلى إجهاد أو التهاب خلايا الكبد.',
    analogy: 'تسرب زيت المحرك على أرضية المرآب عند ارتفاع حرارته.',
    category: 'أمراض الكبد'
  },
  {
    term: 'AST (إنزيم الكبد والعضلات)',
    definition: 'إنزيم يتواجد في الكبد والعضلات وعضلة القلب.',
    whyItMatters: 'ارتفاعه مع ALT يساعد في تقييم صحة الكبد والعضلات.',
    analogy: 'حساس تحذير ثاني مشترك بين المحرك والنظام الكهربائي.',
    category: 'أمراض الكبد'
  },
  {
    term: 'HbA1c (السكر التراكمي)',
    definition: 'فحص يقيس نسبة السكر المرتبط بهيموجلوبين الدم على مدى 2-3 أشهر الماضية.',
    whyItMatters: 'يعطي صورة دقيقة ومستمرة لمستوى التحكم بالسكر.',
    analogy: 'تقرير درجات شهري يوضح معدل السرعة على مدى أشهر بدلاً من لقطة رادار واحدة.',
    category: 'الغدد الصماء والسكر'
  },
  {
    term: 'hs-CRP (بروتين التفاعل C عالي الحساسية)',
    definition: 'بروتين ينتجه الكبد عند وجود التهاب منخفض الحدة في جدران الشرايين.',
    whyItMatters: 'مؤشر على مخاطر الالتهاب الوعائي والقلبي.',
    analogy: 'جهاز إنذار حرائق حساس يلتقط الدخان قبل اشتعال النار.',
    category: 'أمراض القلب والالتهابات'
  },
  {
    term: 'الهيموجلوبين (Hemoglobin)',
    definition: 'بروتين غني بالحديد داخل خلايا الدم الحمراء ينقل الأكسجين لكافة أنحاء الجسم.',
    whyItMatters: 'انخفاضه يسبب فقر الدم والإجهاد.',
    analogy: 'شاحنات توصيل الأكسجين التي تزود كل حي بالطاقة.',
    category: 'أمراض الدم'
  },
  {
    term: 'الصفائح الدموية (Platelets)',
    definition: 'خلايا دموية صغيرة تلتصق ببعضها لوقف النزيف عند إصابة الأوعية الدموية.',
    whyItMatters: 'ضرورية للتجلط الطبيعي والتئام الجروح.',
    analogy: 'عمال طوارئ يصلحون التسريبات والشقوق فور حدوثها.',
    category: 'أمراض الدم'
  },
  {
    term: 'كريات الدم البيضاء (WBC)',
    definition: 'خلايا الجهاز المناعي التي تدافع عن الجسم ضد العدوى البكتيرية والفيروسية.',
    whyItMatters: 'ارتفاعها يشير غالباً إلى وجود التهاب أو عدوى نشطة.',
    analogy: 'قوات الدفاع الداخلي التي تستجيب لإنذارات الأمان.',
    category: 'أمراض الدم والمناعة'
  },
  {
    term: 'TSH (الهرمون المنشط للغدة الدرقية)',
    definition: 'هرمون تفرزه الغدة النخامية لتحفيز الغدة الدرقية على تنظيم الأيض.',
    whyItMatters: 'يساعد في تشخيص خمول أو نشاط الغدة الدرقية.',
    analogy: 'قرص منظم الحرارة الذي يطلب مزيداً أو أقل من التدفئة.',
    category: 'الغدد الصماء'
  },
  {
    term: 'BUN (يوريا الدم)',
    definition: 'فضلات تنتج عن تكسير البروتين في الكبد وتطرح عن طريق الكلى.',
    whyItMatters: 'تقييم وظائف الكلى ومستوى السوائل في الجسم.',
    analogy: 'عادم المحرك الناتج عن عملية الاحتراق.',
    category: 'أمراض الكلى'
  }
];

export function getMedicalGlossary(language: Language): MedicalTerm[] {
  switch (language) {
    case 'fr':
      return GLOSSARY_FR;
    case 'ar':
      return GLOSSARY_AR;
    default:
      return GLOSSARY_EN;
  }
}

export const COMMON_MEDICAL_GLOSSARY = GLOSSARY_EN;
